AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DynamoDBTable1:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LionTable
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBTable2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ElephantTable
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBTable3:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TigerTable
      AttributeDefinitions:
        - AttributeName: ItemID
          AttributeType: S
      KeySchema:
        - AttributeName: ItemID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBTable4:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GiraffeTable
      AttributeDefinitions:
        - AttributeName: RecordID
          AttributeType: S
      KeySchema:
        - AttributeName: RecordID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBTable5:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ZebraTable
      AttributeDefinitions:
        - AttributeName: EntityID
          AttributeType: S
      KeySchema:
        - AttributeName: EntityID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
