AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./s3-buckets.cfn.yaml"

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./ddbs.cfn.yaml"